version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - "./src:/app/src"

  test:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    environment:
      - CI=true
    command: npm test

  watch-test:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: npm test
    volumes:
      - "./src:/app/src"

  prod:
    build:
      context: .
  