FROM node:13.8
WORKDIR /app
COPY . .
RUN npm install
EXPOSE 3000
EXPOSE 35729
CMD ["npm", "run", "start"]
# for hot reloading, run with something like:
# docker run -it -p 3000:3000 -p 35729:35729 -v $(pwd):/app $BUILDNAME